Dev
MrSwed/charts_analyser pull request #1
Opened 2024-03-19 07:04 UTC by MrSwed

2024-03-26 17:27 UTC, Bazys requested changes
пока механическая проверка, потом буду логику проверять. Но пока не увидел где ты применяешь полученные знания в виде worker pool или другие патьерны конкурентности.
много дублирующегося кода - ищи способ унифицировать.

2024-03-26 17:27 UTC, Bazys commented on internal/simulator/service/send.go
> +	if req, err = http.NewRequest("POST", urlStr, bytes.NewBuffer(body)); err != nil {
ты в функцию передаещь контекст, а почему тут не используешь?

2024-03-26 17:27 UTC, Bazys commented on internal/simulator/service/service.go
> +func historyTimeNowFinish(start *time.Time) *time.Time {
зачем эта функция?

2024-03-26 17:27 UTC, Bazys commented on cmd/app/main.go
> +	graceShutdown.Add("DB", func(ctx context.Context) (err error) {
а зачем здесь контекст?

2024-03-26 17:27 UTC, Bazys commented on cmd/app/main.go
> +	graceShutdown.Add("APP", func(ctx context.Context) (err error) {
то же, зачем здесь контекст?

2024-03-26 17:27 UTC, Bazys commented on internal/simulator/service/send.go
> +func (s *RequestService) SendTrack(ctx context.Context, vesselID appDomain.VesselID, location appDomain.Point) {
vesselID - для чего этот параметр?

2024-03-26 17:27 UTC, Bazys commented on internal/app/service/vessel.go
> +func (s *VesselService) SetDeleteVessels(ctx context.Context, delete bool, vesselIDS ...domain.VesselID) error {
```
func (s *VesselService) SetDeleteVessels(ctx context.Context, delete bool, vesselIDs ...domain.VesselID) error {
```

2024-03-26 17:27 UTC, Bazys commented on cmd/simulator/main.go
> +	var ids []int64
количество vessels тебе известно, почему бы сразу не преаллоцировать слайс?

2024-03-26 17:27 UTC, Bazys commented on internal/app/handler/authMiddle.go
> +		claims = u.(*jwt.Token).Claims.(jwt.MapClaims)
а вдруг там совсем не то что ты ожидаешь получить? кто будет проверяить?

2024-03-26 17:27 UTC, Bazys commented on internal/app/repository/log.go
> +	if stmt, err = tx.PreparexContext(ctx, "INSERT INTO"+" "+constant.DBControlLog+
вместо конкатенции строк лучше использовать fmt.Sprintf

2024-03-26 17:27 UTC, Bazys commented on internal/app/domain/state.go
> +	if reflect.ValueOf(src).Kind() == reflect.String {
рефлексия, да и без проверки типов дальше.
есть же конструкция switch v := src.(type)

2024-03-26 17:27 UTC, Bazys commented on internal/app/handler/charts.go
> +func (h *Handler) ChartVessels() fiber.Handler {
дублируюшийся код с internal/app/handler/charts.go:29-51
может вынести общие части?

2024-03-26 18:15 UTC, MrSwed commented on cmd/app/main.go
> +	graceShutdown.Add("DB", func(ctx context.Context) (err error) {
"исторически сложилось" :)
возможность прокинуть контекст в функцию завершения, - использовал аналогичный механизм gracefulshutdown в метриках и корротких ссылках, где нужно было мягко завершить сохранение на диск.. ну и также использовался стандартный [server.Shutdown](https://pkg.go.dev/net/http#Server.Shutdown) до смены gin на fiber, а у него соотв. семантика с использованием контекста

2024-03-26 18:16 UTC, MrSwed commented on cmd/app/main.go
> +	graceShutdown.Add("APP", func(ctx context.Context) (err error) {
ответ тот же)

2024-03-26 18:33 UTC, MrSwed commented on internal/app/repository/log.go
> +	if stmt, err = tx.PreparexContext(ctx, "INSERT INTO"+" "+constant.DBControlLog+
хм.. на одном из вебинаров  было  сравнение скорости разных способов сложения строк..., простое сложение выигрывало у fmt, это конечно медленнее чем с stringbuilder

2024-03-26 18:40 UTC, MrSwed commented on internal/app/handler/charts.go
> +func (h *Handler) ChartVessels() fiber.Handler {
не, там разные функции роуты и соотв. дергают разные сервисы, хоть и очень похожие

2024-03-30 15:10 UTC, Bazys requested changes
теперь давай восстановим свои тесты и сделаем покрытие до 40%

2024-04-03 17:41 UTC, merged